export default function Head() {
  return (
    <>
      <title>HỌC IT CÙNG DEVC</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="shortcut icon" href="/images/logo.png" type="image/x-icon" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
